In [1]:
import numpy as np
a={1,2,3,4,5}
b= np.array(a)
print(a, type(a))
print(b, type(b))

{1, 2, 3, 4, 5} <class 'set'>
{1, 2, 3, 4, 5} <class 'numpy.ndarray'>


In [4]:
b = np.arange(1,10,2)
print(b, type(b), b.shape)

[1 3 5 7 9] <class 'numpy.ndarray'> (5,)


In [5]:
a=[{1,2,3}, {4,5,6}]
b=np.array(a)
print(b, b.shape)

[{1, 2, 3} {4, 5, 6}] (2,)


In [6]:
a=[1,2,3,4,5,6]
b=np.array(a).reshape(2,3)
c=np.array(a).reshape(3,2)
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [9]:
print(b[0])
print(b[1][1])
print(b[:,1])

[1 2 3]
5
[2 5]


In [16]:
a=[{1,2,3}, {4,5,6}]
print(a)
print(b)
# print(a+1)
print(b+1)
print(a*2)
print(b*2)

[{1, 2, 3}, {4, 5, 6}]
[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]
[{1, 2, 3}, {4, 5, 6}, {1, 2, 3}, {4, 5, 6}]
[[ 2  4  6]
 [ 8 10 12]]


In [20]:
aa = [1,2,3,4]
bb=[7,8]
arr1=np.array(aa)
arr2=np.array(bb)
# print(aa+bb)
print(arr1+3)
print(arr1-1)
print(arr1*2)
print(arr1/2)
print(arr1//2)
print(arr1%2)

[4 5 6 7]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[1 0 1 0]


In [22]:
a1=[(1,1,1),(2,2,2),(3,3,3)]
a2=[1,2,3]
b1=np.array(a1)
b2=np.array(a2)
print(b1)
print(b2)
print(b1+b2)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[1 2 3]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [42]:
# mean - 평균, sqrt - 루트(1/2승), log- log(e) = 1
print(np.log(2.71))

0.9969486348916096


In [44]:
a=[5,3,4,2,5,1,7,6,9]
arr1=np.array(a).reshape(3,3)
print(arr1)

[[5 3 4]
 [2 5 1]
 [7 6 9]]


In [47]:
print(np.sort(arr1)) #default는 행기준 정렬
print(np.sort(arr1, axis=1))
print(np.sort(arr1, axis=0))
print(np.sort(arr1, axis=0)[::-1,::]) # 열기준 역순정렬


[[3 4 5]
 [1 2 5]
 [6 7 9]]
[[3 4 5]
 [1 2 5]
 [6 7 9]]
[[2 3 1]
 [5 5 4]
 [7 6 9]]
[[7 6 9]
 [5 5 4]
 [2 3 1]]


In [51]:
print(arr1)
print(arr1.transpose()) #행과 열 변경
print(arr1>5)
print(np.all(arr1>3))
print(np.any(arr1>3))

[[5 3 4]
 [2 5 1]
 [7 6 9]]
[[5 2 7]
 [3 5 6]
 [4 1 9]]
[[False False False]
 [False False False]
 [ True  True  True]]
False
True


In [55]:
# 0과 1로 행렬 생성
a1=np.zeros(10)
a2=np.zeros([3,3])
print(a1)
print(a2)
a1=np.ones(10)
a2=np.ones([3,3])
print(a1)
print(a2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [58]:
print(arr1)
b1=np.ones_like(arr1)
b2=np.zeros_like(arr1)
print(b1)
print(b2)

[[5 3 4]
 [2 5 1]
 [7 6 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
