In [5]:
import numpy as np

In [10]:
data = np.genfromtxt("data/ratings.dat", delimiter="::", dtype=np.int64)
print(data[:10,:])
print(data.shape)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]]
(1000209, 4)


In [12]:
user_ids=np.unique(data[:,0]) # 반복 없애기
print(user_ids[:5])
print(user_ids.shape)

[1 2 3 4 5]
(6040,)


In [13]:
mean_values=[]
for user_id in user_ids:
    data_for_user=data[data[:,0] == user_id, :]
    value=data_for_user[:,2].mean()
    mean_values.append([user_id, value])
mean_values[:10]


[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606]]

In [14]:
mean_array=np.array(mean_values,dtype=np.float32)
print(mean_array[:10])
print(mean_array.shape)

[[ 1.         4.188679 ]
 [ 2.         3.7131784]
 [ 3.         3.9019608]
 [ 4.         4.1904764]
 [ 5.         3.1464646]
 [ 6.         3.9014084]
 [ 7.         4.322581 ]
 [ 8.         3.884892 ]
 [ 9.         3.7358491]
 [10.         4.114713 ]]
(6040, 2)


In [15]:
np.savetxt("data/userid_result.csv", mean_array, fmt="%.2f", delimiter=",")

In [26]:
rating_value=[]
movie_ids = np.unique(data[:,1])
for movie_id in movie_ids:
    data_for_movie = data[data[:,1] == movie_id, :]
    value = data_for_movie[:,2].mean()
    if value >= 4 :
        rating_value.append([movie_id, value])
rating_array = np.array(rating_value, dtype=np.float32)

In [ ]:
np.savetxt("data/moive_result.csv", rating_array, fmt="%.2f", delimiter=",")

In [32]:
print(rating_array[:])

[[1.0000000e+00 4.1468463e+00]
 [1.7000000e+01 4.0275450e+00]
 [2.8000000e+01 4.0558658e+00]
 [2.9000000e+01 4.0620346e+00]
 [4.7000000e+01 4.1064205e+00]
 [5.0000000e+01 4.5171061e+00]
 [5.3000000e+01 4.7500000e+00]
 [5.8000000e+01 4.0938125e+00]
 [1.1000000e+02 4.2349572e+00]
 [1.1100000e+02 4.1838708e+00]
 [1.1600000e+02 4.0975609e+00]
 [1.2100000e+02 4.0540543e+00]
 [1.2800000e+02 4.3333335e+00]
 [1.3000000e+02 4.0000000e+00]
 [1.3400000e+02 4.0000000e+00]
 [1.3900000e+02 4.0000000e+00]
 [1.5000000e+02 4.0735412e+00]
 [1.6200000e+02 4.0631366e+00]
 [2.1300000e+02 4.0569105e+00]
 [2.1400000e+02 4.2500000e+00]
 [2.3200000e+02 4.0751443e+00]
 [2.4600000e+02 4.1885476e+00]
 [2.6000000e+02 4.4536943e+00]
 [2.9300000e+02 4.1061754e+00]
 [2.9600000e+02 4.2782130e+00]
 [3.0600000e+02 4.2275448e+00]
 [3.0700000e+02 4.0987654e+00]
 [3.1800000e+02 4.5545578e+00]
 [3.2600000e+02 4.3442621e+00]
 [3.5600000e+02 4.0879674e+00]
 [3.6300000e+02 4.2580647e+00]
 [3.9600000e+02 4.0000000e+00]
 [3.9800