In [5]:
import numpy as np

In [10]:
data = np.genfromtxt("data/ratings.dat", delimiter="::", dtype=np.int64)
print(data[:10,:])
print(data.shape)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]]
(1000209, 4)


In [12]:
user_ids=np.unique(data[:,0]) # 반복 없애기
print(user_ids[:5])
print(user_ids.shape)

[1 2 3 4 5]
(6040,)


In [ ]:
mean_values=[]
for user_id in user_ids:
    data_for_user=data[data[:,0] == user_id, :]
    value=data_for_user[:,2].mean()
    mean_values.append([user_id, value])
mean_values[:10]
